version: "3"
services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - .:/srv/app
    links:
      - db:db
    env_file: .docker.env
  db:
    image: mysql:5.7
    ports:
      - "13306:3306"
    environment:
      - MYSQL_DATABASE=dockerphp
      - MYSQL_ROOT_PASSWORD=password
